version: "0.2"
env:
  variables:
    TESTING: "true"
    SECRET_TOKEN: "bGFtYmRhX3NxdWFk"
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 408828050075.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - pytest
      - docker build -t entrega-2-repository -f ./Dockerfile .
  post_build:
    commands:
      - docker tag entrega-2-repository:latest 408828050075.dkr.ecr.us-east-2.amazonaws.com/entrega-2-repository:latest
      - docker push 408828050075.dkr.ecr.us-east-2.amazonaws.com/entrega-2-repository:latest
      - printf '[{"name":"Container-Entrega-3","imageUri":"408828050075.dkr.ecr.us-east-2.amazonaws.com/entrega-2-repository:latest"}]' > imagedefinitions.json
      - printf '{"ImageURI":"408828050075.dkr.ecr.us-east-2.amazonaws.com/entrega-2-repository:latest"}' > imageDetail.json
      - cat imagedefinitions.json
artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
    - imageDetail.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json